"""Independent symbolic derivation of the spatial and dual crane equations.

The numeric assembler in ``cranebench.plants.base`` and this file share no
code: the assembler differentiates a kinematic declaration numerically, while
this script builds a Lagrangian symbolically and hands it to SymPy's
``LagrangesMethod``, a third-party implementation.  Agreement between the two
is therefore evidence about the model rather than about one implementation.

Run it to regenerate ``cranebench/plants/_generated.py``:

    python tools/derive_symbolic.py

The generated module is committed so that users need neither SymPy nor the
derivation time, and so that a reviewer can read the equations that are
actually evaluated.
"""

from __future__ import annotations

import pathlib
import textwrap

import sympy as sp
from sympy.physics.mechanics import LagrangesMethod, dynamicsymbols

G = sp.Rational(980665, 100000)          # 9.80665, kept exact


def _eom(T, V, qs, params):
    """Return (M, forcing) with M(q) qdd = forcing(q, qd) for the free system."""
    L = sp.simplify(T - V)
    lm = LagrangesMethod(L, qs)
    lm.form_lagranges_equations()
    return lm.mass_matrix, lm.forcing


def spatial():
    t = sp.Symbol("t")
    x, y, l, th, ph, psi = [dynamicsymbols(n) for n in
                            ("x", "y", "l", "th", "ph", "psi")]
    qs = [x, y, l, th, ph, psi]
    mb, mt, mp, mw, izz, kpsi = sp.symbols("m_bridge m_trolley m_payload m_winch izz k_psi",
                                           positive=True)
    st, ct, sp_, cp = sp.sin(th), sp.cos(th), sp.sin(ph), sp.cos(ph)
    bodies = [
        (mb, sp.Matrix([0, y, 0])),
        (mt, sp.Matrix([x, y, 0])),
        (mp, sp.Matrix([x + l * st * cp, y + l * sp_, -l * ct * cp])),
    ]
    T = 0
    for m, p in bodies:
        v = p.diff(t)
        T += sp.Rational(1, 2) * m * (v.T * v)[0]
    T += sp.Rational(1, 2) * mw * l.diff(t) ** 2
    T += sp.Rational(1, 2) * izz * psi.diff(t) ** 2
    V = -mp * G * l * ct * cp + sp.Rational(1, 2) * kpsi * psi ** 2
    return qs, (mb, mt, mp, mw, izz, kpsi), _eom(T, V, qs, None)


def dual():
    """Smooth branch only: both falls taut, so max(0, .) is differentiable."""
    t = sp.Symbol("t")
    x1, x2, xc, zc, al = [dynamicsymbols(n) for n in ("x1", "x2", "xc", "zc", "al")]
    qs = [x1, x2, xc, zc, al]
    mt, mbm, Lb, H, k, rest = sp.symbols(
        "m_trolley m_beam length height k_cable rest", positive=True)
    r = Lb / 2
    ca, sa = sp.cos(al), sp.sin(al)
    bodies = [(mt, sp.Matrix([x1, 0, H])), (mt, sp.Matrix([x2, 0, H])),
              (mbm, sp.Matrix([xc, 0, zc]))]
    T = 0
    for m, p in bodies:
        v = p.diff(t)
        T += sp.Rational(1, 2) * m * (v.T * v)[0]
    T += sp.Rational(1, 2) * (mbm * Lb ** 2 / 12) * al.diff(t) ** 2
    V = mbm * G * zc
    for sgn, xt in ((-1, x1), (1, x2)):
        A = sp.Matrix([xc + sgn * r * ca, zc + sgn * r * sa])
        Tp = sp.Matrix([xt, H])
        d = A - Tp
        ln = sp.sqrt((d.T * d)[0])
        V += sp.Rational(1, 2) * k * (ln - rest) ** 2
    return qs, (mt, mbm, Lb, H, k, rest), _eom(T, V, qs, None)


HEADER = '''"""Generated by tools/derive_symbolic.py -- do not edit by hand.

Closed-form mass matrix and bias vector for the spatial and dual cranes,
obtained by an independent symbolic derivation (SymPy ``LagrangesMethod``).
Used as a fast path; the numeric assembler remains the reference implementation
and ``tests/test_symbolic.py`` requires the two to agree.

Convention: ``M(q) qdd = forcing(q, qd) + Q``, where ``Q`` is the vector of
non-conservative generalised forces supplied by the plant.
"""

import numpy as np
from numpy import cos, sin, sqrt


'''


def emit(name, qs, params, MF):
    M, F = MF
    args = [sp.Symbol(str(q.func)) for q in qs]
    dargs = [sp.Symbol("d" + str(q.func)) for q in qs]
    subs = {}
    for q, a, da in zip(qs, args, dargs):
        subs[q.diff(sp.Symbol("t"))] = da
        subs[q] = a
    Ms = M.subs(subs)
    Fs = F.subs(subs)
    sig = ", ".join(str(a) for a in args + dargs + [str(p) for p in params])
    body = []
    first = str(args[0])
    body.append(f"def {name}_M({sig}):")
    body.append(f"    _n = np.shape(np.asarray({first}))")
    body.append("    M = np.zeros(_n + (%d, %d))" % (M.rows, M.cols))
    for i in range(M.rows):
        for j in range(M.cols):
            e = sp.simplify(Ms[i, j])
            if e == 0:
                continue
            body.append(f"    M[..., {i}, {j}] = {sp.pycode(e)}")
    body.append("    return M")
    body.append("")
    body.append(f"def {name}_bias({sig}):")
    body.append(f"    _n = np.shape(np.asarray({first}))")
    body.append("    f = np.zeros(_n + (%d,))" % F.rows)
    for i in range(F.rows):
        e = sp.simplify(Fs[i])
        if e == 0:
            continue
        body.append(f"    f[..., {i}] = {sp.pycode(e)}")
    body.append("    return f")
    body.append("")
    return "\n".join(body)


if __name__ == "__main__":
    out = HEADER
    for nm, fn in (("spatial", spatial), ("dual", dual)):
        print(f"deriving {nm} ...", flush=True)
        qs, params, MF = fn()
        out += emit(nm, qs, params, MF) + "\n"
    dst = pathlib.Path(__file__).resolve().parents[1] / "cranebench" / "plants" / "_generated.py"
    dst.write_text(out, encoding="utf-8")
    print("written", dst, len(out), "bytes")
